import{Base,copy,clamp,COLORS}from'./base.js';
export const W=3600,H=3600,SPACING=9;
export const wrap=(v,size)=>((v%size)+size)%size;export const delta=(a,b,size)=>((a-b+size*1.5)%size)-size/2;
const norm=a=>Math.atan2(Math.sin(a),Math.cos(a));
export class Game extends Base{
 constructor(players=[],saved=null,options={}){super();this.setup(players,{seconds:[60,120,180].includes(options.seconds)?options.seconds:120,bots:[0,2,4].includes(options.bots)?options.bots:2,arena:['garden','lagoon','twilight'].includes(options.arena)?options.arena:'garden',seed:options.seed||0});Object.defineProperty(this,'foodIndex',{value:null,writable:true});this.kind='serpents';this.interval=1/20;this.arena=this.options.arena;for(let i=0;i<this.options.bots;i++)this.players.push({id:'bot-'+i,number:9+i,color:COLORS[(i+3)%8],bot:true,score:0,deaths:0,energy:100});this.food=[];this.players.forEach((p,i)=>this.spawn(p,i));for(let i=0;i<420;i++)this.addFood();this.emit('round');this.restore(saved);this.foodIndex=null;}
 spawn(p,index){const angle=index/Math.max(1,this.players.length)*Math.PI*2,x=W/2+Math.cos(angle)*520,y=H/2+Math.sin(angle)*520,dir=angle+Math.PI;Object.assign(p,{x,y,angle:dir,desired:dir,alive:true,mass:18,score:18,body:Array.from({length:18},(_,i)=>[x-Math.cos(dir)*i*SPACING,y-Math.sin(dir)*i*SPACING]),immuneUntil:this.time+2.5,respawn:0,boost:false,inputUntil:0,foodClock:0,sprinting:false,botClock:0,target:null});}
 addFood(x,y,value=1){if(this.food.length>=700)return;const p={x:x===undefined?this.random()*W:wrap(x,W),y:y===undefined?this.random()*H:wrap(y,H),value,color:Math.floor(this.random()*6)};this.food.push(p);this.foodIndex=null;}
 action(id,action,value={}){const p=this.input(id,action,value);if(!p)return;if(Math.hypot(value.x,value.y)>.15)p.desired=Math.atan2(value.y,value.x);}
 steerBot(p){let best=p.target,d=best?delta(best.x,p.x,W)**2+delta(best.y,p.y,H)**2:Infinity;if(!best||d<900){best=null;d=Infinity;for(let i=0;i<40;i++){const f=this.food[Math.floor(this.random()*this.food.length)];if(!f)continue;const dist=delta(f.x,p.x,W)**2+delta(f.y,p.y,H)**2;if(dist<d){d=dist;best=f;}}p.target=best;}let a=best?Math.atan2(delta(best.y,p.y,H),delta(best.x,p.x,W)):p.angle;for(const other of this.players){if(!other.alive||other===p)continue;for(let i=0;i<other.body.length;i+=3){const b=other.body[i],dx=delta(b[0],p.x,W),dy=delta(b[1],p.y,H);if(dx*dx+dy*dy<4900&&Math.abs(norm(Math.atan2(dy,dx)-p.angle))<.8){a=p.angle+Math.PI/2;break;}}}p.desired=a;}
 move(p,dt){if(p.bot){p.botClock-=dt;if(p.botClock<=0){this.steerBot(p);p.botClock=.25;}}p.sprinting=p.boost&&p.inputUntil>this.time&&p.mass>20;p.angle+=clamp(norm(p.desired-p.angle),-3.5*dt,3.5*dt);const speed=p.sprinting?320:185;p.x=wrap(p.x+Math.cos(p.angle)*speed*dt,W);p.y=wrap(p.y+Math.sin(p.angle)*speed*dt,H);let head=p.body[0];if(!head)p.body.push([p.x,p.y]);else{let dx=delta(p.x,head[0],W),dy=delta(p.y,head[1],H),distance=Math.hypot(dx,dy);while(distance>=SPACING){head=[wrap(head[0]+dx/distance*SPACING,W),wrap(head[1]+dy/distance*SPACING,H)];p.body.unshift(head);dx=delta(p.x,head[0],W);dy=delta(p.y,head[1],H);distance=Math.hypot(dx,dy);}}while(p.body.length>Math.floor(p.mass))p.body.pop();if(p.sprinting){p.foodClock+=dt;if(p.foodClock>=.2){p.foodClock=0;p.mass=Math.max(18,p.mass-1);const tail=p.body.at(-1);this.addFood(tail[0],tail[1],1);}}p.score=Math.floor(p.mass);p.energy=clamp((p.mass-18)*4,0,100);}
 crash(p){if(!p.alive)return;p.alive=false;p.boost=false;p.sprinting=false;p.respawn=3;p.deaths++;for(let i=0;i<p.body.length;i+=3)this.addFood(p.body[i][0],p.body[i][1],2);this.emit('crash',{player:p.id,x:p.x,y:p.y,color:p.color});}
 step(dt){this.time+=dt;this.left=Math.max(0,this.left-dt);for(const [i,p]of this.players.entries()){if(!p.alive){p.respawn-=dt;if(p.respawn<=0)this.spawn(p,i);continue;}this.move(p,dt);}const doomed=new Set,grid=new Map,foodGrid=this.foodIndex||new Map;const add=(map,x,y,size,item)=>{const key=Math.floor(x/size)+':'+Math.floor(y/size);if(!map.has(key))map.set(key,[]);map.get(key).push(item);};const near=(map,x,y,size)=>{const count=W/size,cx=Math.floor(x/size),cy=Math.floor(y/size),out=[];for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)out.push(...(map.get(((cx+a+count)%count)+':'+((cy+b+count)%count))||[]));return out;};for(const q of this.players){if(!q.alive||q.immuneUntil>this.time)continue;add(grid,q.x,q.y,40,{id:q.id,x:q.x,y:q.y,head:true});for(let i=1;i<q.body.length;i++)add(grid,q.body[i][0],q.body[i][1],40,{id:q.id,x:q.body[i][0],y:q.body[i][1],head:false});}for(const p of this.players){if(!p.alive||p.immuneUntil>this.time)continue;for(const q of near(grid,p.x,p.y,40)){if(q.id===p.id)continue;const dist=delta(q.x,p.x,W)**2+delta(q.y,p.y,H)**2;if(dist<(q.head?400:196)){doomed.add(p.id);if(q.head)doomed.add(q.id);}}}for(const p of this.players)if(doomed.has(p.id))this.crash(p);if(!this.foodIndex){foodGrid.clear();for(const f of this.food)add(foodGrid,f.x,f.y,60,f);this.foodIndex=foodGrid;}const eaten=new Set;for(const p of this.players){if(!p.alive)continue;for(const f of near(foodGrid,p.x,p.y,60)){if(eaten.has(f)||delta(p.x,f.x,W)**2+delta(p.y,f.y,H)**2>=324)continue;p.mass=Math.min(100,p.mass+f.value);p.score=Math.floor(p.mass);eaten.add(f);this.emit('eat',{player:p.id,x:f.x,y:f.y});}}if(eaten.size){this.food=this.food.filter(f=>!eaten.has(f));this.foodIndex=null;}while(this.food.length<420)this.addFood();if(this.left<=0)this.finish();}
 snapshot(id){const leader=this.players.filter(p=>p.alive).sort((a,b)=>b.mass-a.mass||a.number-b.number)[0];const own=this.players.find(p=>p.id===id),visible=(x,y)=>own&&Math.abs(delta(x,own.x,W))<650&&Math.abs(delta(y,own.y,H))<1100;const players=this.players.map(({inputUntil,desired,boost,target,botClock,body,...p})=>({...p,body:own?body.filter(b=>visible(...b)).map(b=>b.slice()):p.id===leader?.id?body.filter((b,i)=>i%Math.max(1,Math.ceil(body.length/60))===0||i===body.length-1).map(b=>b.map(Math.round)):[]}));return{kind:this.kind,world:{w:W,h:H,torus:true},phase:this.phase,time:this.time,left:this.left,round:1,rounds:1,arena:this.arena,walls:[],food:own?this.food.filter(f=>visible(f.x,f.y)).map(f=>({...f})):[],players,events:copy(this.events),winner:this.winner,winners:this.winners,options:this.options,you:id||null};}
}
