import{InterestIndex}from'./interest.js';
import{Base,copy,clamp,COLORS}from'./base.js';
export const W=3600,H=3600,SPACING=9;
export const wrap=(v,size)=>((v%size)+size)%size;export const delta=(a,b,size)=>((a-b+size*1.5)%size)-size/2;
const norm=a=>Math.atan2(Math.sin(a),Math.cos(a)),wirePosition=x=>Math.round(x*4)/4;
export class Game extends Base{
 constructor(players=[],saved=null,options={}){super();this.setup(players,{seconds:[60,120,180].includes(options.seconds)?options.seconds:120,bots:[0,2,4].includes(options.bots)?options.bots:2,arena:['garden','lagoon','twilight'].includes(options.arena)?options.arena:'garden',seed:options.seed||0});Object.defineProperty(this,'foodIndex',{value:null,writable:true});Object.defineProperty(this,'interest',{value:new InterestIndex,writable:true});this.viewports={};this.nextFoodId=1;this.kind='serpents';this.interval=1/20;this.arena=this.options.arena;for(let i=0;i<this.options.bots;i++)this.players.push({id:'bot-'+i,number:9+i,color:COLORS[(i+3)%8],bot:true,score:0,deaths:0,energy:100});this.food=[];this.players.forEach((p,i)=>this.spawn(p,i));for(let i=0;i<420;i++)this.addFood();this.emit('round');this.restore(saved);this.foodIndex=null;this.interest=new InterestIndex;this.viewports={};for(const f of this.food){if(!Number.isSafeInteger(f.id))f.id=this.nextFoodId++;else this.nextFoodId=Math.max(this.nextFoodId,f.id+1);}for(const p of this.players){if(p.body.some(b=>b.length!==3)){p.body=p.body.map((b,i)=>[b[0],b[1],0-i]);p.pathSequence=0;}}this.interestRevision=0;}
 spawn(p,index){const angle=index/Math.max(1,this.players.length)*Math.PI*2,x=W/2+Math.cos(angle)*520,y=H/2+Math.sin(angle)*520,dir=angle+Math.PI;Object.assign(p,{x,y,angle:dir,desired:dir,alive:true,mass:18,score:18,pathSequence:0,body:Array.from({length:18},(_,i)=>[x-Math.cos(dir)*i*SPACING,y-Math.sin(dir)*i*SPACING,0-i]),immuneUntil:this.time+2.5,respawn:0,boost:false,inputUntil:0,foodClock:0,sprinting:false,botClock:0,target:null});}
 addFood(x,y,value=1){if(this.food.length>=700)return;const p={id:this.nextFoodId++,x:x===undefined?this.random()*W:wrap(x,W),y:y===undefined?this.random()*H:wrap(y,H),value,color:Math.floor(this.random()*6)};this.food.push(p);this.foodIndex=null;}
 action(id,action,value={}){if(action==='viewport'){if(!this.players.some(p=>p.id===id&&!p.bot))throw Error('spectator');if(!Number.isFinite(value.width)||!Number.isFinite(value.height))throw Error('invalidInput');this.viewports[id]={width:clamp(Math.round(value.width),320,1800),height:clamp(Math.round(value.height),320,2800)};return;}const p=this.input(id,action,value);if(!p)return;if(Math.hypot(value.x,value.y)>.15)p.desired=Math.atan2(value.y,value.x);}
 steerBot(p){let best=p.target,d=best?delta(best.x,p.x,W)**2+delta(best.y,p.y,H)**2:Infinity;if(!best||d<900){best=null;d=Infinity;for(let i=0;i<40;i++){const f=this.food[Math.floor(this.random()*this.food.length)];if(!f)continue;const dist=delta(f.x,p.x,W)**2+delta(f.y,p.y,H)**2;if(dist<d){d=dist;best=f;}}p.target=best;}let a=best?Math.atan2(delta(best.y,p.y,H),delta(best.x,p.x,W)):p.angle;for(const other of this.players){if(!other.alive)continue;for(let i=other===p?3:0;i<other.body.length;i+=3){const b=other.body[i],dx=delta(b[0],p.x,W),dy=delta(b[1],p.y,H);if(dx*dx+dy*dy<4900&&Math.abs(norm(Math.atan2(dy,dx)-p.angle))<.8){a=p.angle+Math.PI/2;break;}}}p.desired=a;}
 move(p,dt){if(p.bot){p.botClock-=dt;if(p.botClock<=0){this.steerBot(p);p.botClock=.25;}}p.sprinting=p.boost&&p.inputUntil>this.time&&p.mass>20;p.angle+=clamp(norm(p.desired-p.angle),-3.5*dt,3.5*dt);const speed=p.sprinting?320:185;p.x=wrap(p.x+Math.cos(p.angle)*speed*dt,W);p.y=wrap(p.y+Math.sin(p.angle)*speed*dt,H);let head=p.body[0];if(!head)p.body.push([p.x,p.y,++p.pathSequence]);else{let dx=delta(p.x,head[0],W),dy=delta(p.y,head[1],H),distance=Math.hypot(dx,dy);while(distance>=SPACING){head=[wrap(head[0]+dx/distance*SPACING,W),wrap(head[1]+dy/distance*SPACING,H),++p.pathSequence];p.body.unshift(head);dx=delta(p.x,head[0],W);dy=delta(p.y,head[1],H);distance=Math.hypot(dx,dy);}}while(p.body.length>Math.floor(p.mass))p.body.pop();if(p.sprinting){p.foodClock+=dt;if(p.foodClock>=.2){p.foodClock=0;p.mass=Math.max(18,p.mass-1);const tail=p.body.at(-1);this.addFood(tail[0],tail[1],1);}}p.score=Math.floor(p.mass);p.energy=clamp((p.mass-18)*4,0,100);}
 crash(p){if(!p.alive)return;p.alive=false;p.boost=false;p.sprinting=false;p.respawn=3;p.deaths++;for(let i=0;i<p.body.length;i+=3)this.addFood(p.body[i][0],p.body[i][1],2);this.emit('crash',{player:p.id,x:p.x,y:p.y,color:p.color});}
 step(dt){this.interestRevision++;this.time+=dt;this.left=Math.max(0,this.left-dt);for(const [i,p]of this.players.entries()){if(!p.alive){p.respawn-=dt;if(p.respawn<=0)this.spawn(p,i);continue;}this.move(p,dt);}const doomed=new Set,grid=new Map,foodGrid=this.foodIndex||new Map;const add=(map,x,y,size,item)=>{const key=Math.floor(x/size)+':'+Math.floor(y/size);if(!map.has(key))map.set(key,[]);map.get(key).push(item);};const near=(map,x,y,size)=>{const count=W/size,cx=Math.floor(x/size),cy=Math.floor(y/size),out=[];for(let a=-1;a<=1;a++)for(let b=-1;b<=1;b++)out.push(...(map.get(((cx+a+count)%count)+':'+((cy+b+count)%count))||[]));return out;};for(const q of this.players){if(!q.alive||q.immuneUntil>this.time)continue;add(grid,q.x,q.y,40,{id:q.id,x:q.x,y:q.y,head:true});for(let i=1;i<q.body.length;i++)add(grid,q.body[i][0],q.body[i][1],40,{id:q.id,x:q.body[i][0],y:q.body[i][1],head:false,segment:i});}for(const p of this.players){if(!p.alive||p.immuneUntil>this.time)continue;for(const q of near(grid,p.x,p.y,40)){if(q.id===p.id&&(q.head||q.segment<3))continue;const dist=delta(q.x,p.x,W)**2+delta(q.y,p.y,H)**2;if(dist<(q.head?400:196)){doomed.add(p.id);if(q.head)doomed.add(q.id);}}}for(const p of this.players)if(doomed.has(p.id))this.crash(p);if(!this.foodIndex){foodGrid.clear();for(const f of this.food)add(foodGrid,f.x,f.y,60,f);this.foodIndex=foodGrid;}const eaten=new Set;for(const p of this.players){if(!p.alive)continue;for(const f of near(foodGrid,p.x,p.y,60)){if(eaten.has(f)||delta(p.x,f.x,W)**2+delta(p.y,f.y,H)**2>=324)continue;p.mass=Math.min(100,p.mass+f.value);p.score=Math.floor(p.mass);eaten.add(f);this.emit('eat',{player:p.id,x:f.x,y:f.y});}}if(eaten.size){this.food=this.food.filter(f=>!eaten.has(f));this.foodIndex=null;}while(this.food.length<420)this.addFood();if(this.left<=0)this.finish();}
 snapshot(id){
 const own=this.players.find(p=>p.id===id),world={w:W,h:H,torus:true},leader=this.players.filter(p=>p.alive).sort((a,b)=>b.mass-a.mass||a.number-b.number)[0];
 let view;if(own){this.interest.sync(this.players,this.food,world,this.interestRevision);view=this.interest.view(own,this.viewports[id]||{width:900,height:1800},world);}
 const players=this.players.map(p=>{const body=own?(view.bodies.get(p.id)||[]).map(b=>[wirePosition(b[0]),wirePosition(b[1]),b[2]]):p.id===leader?.id?p.body.filter((b,i)=>i%Math.max(1,Math.ceil(p.body.length/60))===0||i===p.body.length-1).map(b=>b.map(Math.round)):[];
 const visible=!own||p.id===id||body.length>0||view.contains(p.x,p.y);
 const common={id:p.id,number:p.number,color:p.color,bot:!!p.bot,score:p.score,alive:p.alive,mass:p.mass,energy:p.energy,deaths:p.deaths,respawn:p.respawn,visible,body};
 return visible?{...common,x:wirePosition(p.x),y:wirePosition(p.y),angle:Math.round(p.angle*10000)/10000,sprinting:p.sprinting,immuneUntil:p.immuneUntil}:common;});
 return {kind:this.kind,world,phase:this.phase,time:this.time,left:this.left,round:1,rounds:1,arena:this.arena,walls:[],food:view?view.food.map(f=>({...f,x:wirePosition(f.x),y:wirePosition(f.y)})):[],players,events:copy(this.events.filter(e=>!view||e.x===undefined||e.player===id||view.contains(e.x,e.y))),winner:this.winner,winners:this.winners,options:this.options,you:id||null};
 }
}
