import {MAJOR_RADIUS as TORUS_MAJOR_RADIUS,MINOR_RADIUS as TORUS_MINOR_RADIUS,surface,followCamera,cameraSpace,clipNear} from './torus-camera.js';
const colors=['#ed8380','#e3a35c','#aea0e0','#edb8d2','#f2d779','#a9d87d'];
export class Scene{
 constructor(canvas){this.canvas=canvas;canvas.width=1200;canvas.height=720;this.c=canvas.getContext('2d');this.t=0;this.prev=performance.now();this.positions=new Map;this.seen=0;this.effects=[];this.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;this.loop=this.loop.bind(this);this.frame=requestAnimationFrame(this.loop);}
 update(s,profiles,paused,role,you){this.role=role;this.you=you;if(this.s?.round!==s.round)this.positions.clear();this.s=s;this.profiles=profiles;this.paused=paused;for(const e of s.events){if(e.id>this.seen&&s.time-e.time<1&&['crash','eat'].includes(e.type)){this.effects.push({...e,life:.65});}this.seen=Math.max(this.seen,e.id);}}
 loop(now){const dt=Math.min(.05,(now-this.prev)/1000);this.prev=now;if(!this.paused&&!this.reduced)this.t+=dt;const interval=this.role==='controller'&&this.s?.kind!=='serpents'?55:33;if(this.s&&(!this.lastDraw||now-this.lastDraw>=interval)){const elapsed=Math.min(.1,(now-(this.lastDraw||now))/1000);this.lastDraw=now;this.draw(elapsed);}this.frame=requestAnimationFrame(this.loop);}
 destroy(){cancelAnimationFrame(this.frame);}
 point(cell){return[(cell%this.s.world.w+.5)*this.sx,(Math.floor(cell/this.s.world.w)+.5)*this.sy];}
 draw(dt){if(this.s.kind==='serpents'){this.drawSerpents(dt);return;}const isPhone=this.role==='controller';if(this.canvas.width!==(isPhone?600:1200)){this.canvas.width=isPhone?600:1200;this.canvas.height=isPhone?360:720;}this.c.setTransform(isPhone?.5:1,0,0,isPhone?.5:1,0,0);const s=this.s,c=this.c,neon=s.kind==='lightcycles',smooth=s.kind==='serpents';this.sx=1200/s.world.w;this.sy=720/s.world.h;const palette=s.arena==='lagoon'||s.arena==='pond'?['#173f54','#39767b']:s.arena==='twilight'?['#282c4b','#6d5578']:['#1f453e','#527760'];const g=c.createLinearGradient(0,0,1200,720);g.addColorStop(0,neon?'#101b39':palette[0]);g.addColorStop(1,neon?'#071a2a':palette[1]);c.fillStyle=g;c.fillRect(0,0,1200,720);
 if(neon){c.strokeStyle='#3da8bf18';c.lineWidth=1;for(let x=0;x<=1200;x+=this.sx){c.beginPath();c.moveTo(x,0);c.lineTo(x,720);c.stroke();}for(let y=0;y<=720;y+=this.sy){c.beginPath();c.moveTo(0,y);c.lineTo(1200,y);c.stroke();}c.strokeStyle='#69dfe85c';c.lineWidth=5;c.strokeRect(3,3,1194,714);for(let i=0;i<8;i++){c.fillStyle='#74dbe4';c.fillRect(i*160+20,1,40,3);c.fillRect(i*160+70,716,40,3);}}
 else{for(let i=0;i<80;i++){const x=(i*137.31)%1200,y=(i*91.7)%720;c.fillStyle=i%2?'#c4d69709':'#1b503e22';c.beginPath();c.ellipse(x,y,20+i%15,9+i%8,i,0,7);c.fill();}for(let i=0;i<25;i++){c.fillStyle='#dfe7b725';const x=(i*231+Math.sin(this.t+i)*6)%1200,y=(i*157+Math.cos(this.t*.5+i)*7)%720;c.beginPath();c.arc(x,y,1.8,0,7);c.fill();}c.strokeStyle='#c2d6a549';c.lineWidth=12;c.strokeRect(6,6,1188,708);}
 for(const cell of s.walls){const[x,y]=this.point(cell);c.fillStyle=neon?'#304266':s.arena==='pond'?'#5298af':'#7d9a69';c.fillRect(x-this.sx*.49,y-this.sy*.49,this.sx*.98,this.sy*.98);c.strokeStyle=neon?'#a396ff':'#bcd3a16b';c.lineWidth=1;c.strokeRect(x-this.sx*.42,y-this.sy*.42,this.sx*.84,this.sy*.84);}
 for(const f of s.food){const[x,y]=smooth?[f.x,f.y]:this.point(f.cell),r=smooth?3.8+f.value:6+f.value;c.fillStyle=colors[f.color%6];if(smooth){c.shadowColor=c.fillStyle;c.shadowBlur=7;}c.beginPath();c.arc(x,y,r,0,7);c.fill();c.shadowBlur=0;c.fillStyle='#fff9';c.beginPath();c.arc(x-r*.25,y-r*.3,r*.24,0,7);c.fill();if(!smooth){c.strokeStyle='#bbe896';c.lineWidth=3;c.beginPath();c.moveTo(x,y-r+1);c.quadraticCurveTo(x+2,y-r-8,x+8,y-r-5);c.stroke();}}
 for(const p of s.players){if(!p.alive&&!neon)continue;let body=smooth?p.body:p.body.map(cell=>this.point(cell));const head=smooth?[p.x,p.y]:[(p.x+.5)*this.sx,(p.y+.5)*this.sy];let pos=this.positions.get(p.id);if(!pos||!p.alive||Math.hypot(pos[0]-head[0],pos[1]-head[1])>160){pos=head.slice();this.positions.set(p.id,pos);}const lerp=this.reduced?1:1-Math.exp(-dt*22);pos[0]+=(head[0]-pos[0])*lerp;pos[1]+=(head[1]-pos[1])*lerp;const angle=smooth?p.angle:p.dir*Math.PI/2;
 c.save();c.globalAlpha=p.alive?1:.38;c.lineCap='round';c.lineJoin='round';if(neon){c.strokeStyle=p.color;c.shadowColor=p.color;c.shadowBlur=this.reduced?0:10;c.lineWidth=this.sx*.65;c.beginPath();body.forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));if(p.alive)c.lineTo(pos[0],pos[1]);c.stroke();c.shadowBlur=0;c.strokeStyle='#f4ffffb0';c.lineWidth=2;c.stroke();}
 else if(smooth){c.strokeStyle='#15383f70';c.lineWidth=24;c.beginPath();[...body].reverse().forEach(([x,y],i)=>i?c.lineTo(x,y+3):c.moveTo(x,y+3));c.lineTo(pos[0],pos[1]+3);c.stroke();c.strokeStyle=p.color;c.lineWidth=p.sprinting?16:20;c.beginPath();[...body].reverse().forEach(([x,y],i)=>i?c.lineTo(x,y):c.moveTo(x,y));c.lineTo(pos[0],pos[1]);c.stroke();c.strokeStyle='#fff3';c.lineWidth=4;c.stroke();for(let i=3;i<body.length;i+=5){const b=body[i];c.fillStyle='#274c5544';c.beginPath();c.arc(b[0],b[1],3,0,7);c.fill();}}
 else{for(let i=body.length-1;i>=0;i--){const b=i?body[i]:pos;c.fillStyle='#152b3855';c.beginPath();c.ellipse(b[0],b[1]+5,10,8,0,0,7);c.fill();if(i%2===0){c.strokeStyle='#253e47';c.lineWidth=3;c.beginPath();c.moveTo(b[0]-10,b[1]+7);c.lineTo(b[0]-13,b[1]+11);c.moveTo(b[0]+10,b[1]+7);c.lineTo(b[0]+13,b[1]+11);c.stroke();}c.fillStyle=p.color;c.beginPath();c.arc(b[0],b[1],this.sx*.4,0,7);c.fill();c.fillStyle='#fff3';c.beginPath();c.arc(b[0]-3,b[1]-4,3,0,7);c.fill();}}
 if(p.alive){c.translate(pos[0],pos[1]);c.rotate(angle);if(neon){c.fillStyle='#f3ffff';c.fillRect(-8,-6,14,12);c.fillStyle=p.color;c.fillRect(-5,-8,8,16);c.fillStyle='#122d43';c.fillRect(1,-3,8,6);if(p.sprinting){c.fillStyle='#fff6a5';c.beginPath();c.moveTo(-9,-5);c.lineTo(-24-Math.sin(this.t*20)*5,0);c.lineTo(-9,5);c.fill();}}
 else{c.fillStyle=p.color;c.beginPath();c.arc(0,0,smooth?12:12.5,0,7);c.fill();for(const y of [-6,6]){c.fillStyle='#fffbe3';c.beginPath();c.ellipse(6,y,5,4,0,0,7);c.fill();c.fillStyle='#173e4b';c.beginPath();c.arc(8,y,2,0,7);c.fill();}if(!smooth){c.strokeStyle='#edecb6';c.lineWidth=2;c.beginPath();c.moveTo(6,-8);c.lineTo(15,-15);c.moveTo(6,8);c.lineTo(15,15);c.stroke();}}}c.restore();if(p.alive){c.font='bold 13px Trebuchet MS,Arial';c.textAlign='center';const name=(this.profiles[p.id]?.name|| (p.bot?'Bot '+(p.number-8):'#'+p.number)).slice(0,14);c.lineWidth=4;c.strokeStyle='#13323bdd';c.strokeText(name,pos[0],pos[1]-22);c.fillStyle='#fff5d7';c.fillText(name,pos[0],pos[1]-22);if(p.immuneUntil>s.time&&smooth){c.strokeStyle='#fff8';c.lineWidth=1;c.setLineDash([3,5]);c.beginPath();c.arc(pos[0],pos[1],22,0,7);c.stroke();c.setLineDash([]);}}}
 for(const e of this.effects){if(!this.paused)e.life-=dt;if(this.reduced)continue;const x=e.x*this.sx,y=e.y*this.sy,r=(1-e.life/.65)*60;c.globalAlpha=Math.max(0,e.life/.65);c.strokeStyle=e.color||'#e5efb8';c.lineWidth=3;c.beginPath();c.arc(x,y,r,0,7);c.stroke();if(e.type==='crash')for(let i=0;i<10;i++){c.fillStyle=e.color||'#fff';c.fillRect(x+Math.cos(i*.628)*r-2,y+Math.sin(i*.628)*r-2,4,4);}c.globalAlpha=1;}this.effects=this.effects.filter(e=>e.life>0);if(s.phase==='finished'&&!this.reduced){for(let i=0;i<65;i++){c.fillStyle=colors[i%6];c.fillRect((i*157+this.t*13)%1200,(i*97+this.t*55)%760-20,5,9);}}}
 avatar(p,x,y,r=13,alpha=1){const c=this.c,profile=this.profiles[p.id],url=profile?.avatar;this.images||=new Map;if(url&&/^\/(play\/)?avatars\/[a-f0-9]{64}\.jpg$/.test(url)&&!this.images.has(url)){const img=new Image;img.src=url;this.images.set(url,img);}const image=this.images.get(url);c.save();c.globalAlpha=alpha;c.fillStyle=p.color;c.strokeStyle='#f7f4d9';c.lineWidth=2;c.beginPath();c.arc(x,y,r,0,7);c.fill();c.stroke();if(image?.complete&&image.naturalWidth){c.clip();c.drawImage(image,x-r,y-r,2*r,2*r);}else{c.fillStyle='#193945';c.font='bold '+Math.max(10,r)+'px Arial';c.textAlign='center';c.textBaseline='middle';c.fillText(String(p.number),x,y);}c.restore();}
 drawSerpents(dt){const s=this.s,c=this.c,W=s.world.w,H=s.world.h,delta=(a,b,n)=>((a-b+n*1.5)%n)-n/2,phone=this.role==='controller';for(const e of this.effects)if(!this.paused)e.life-=dt;this.effects=this.effects.filter(e=>e.life>0);if(phone){const height=Math.max(500,Math.round(800*(this.canvas.clientHeight||500)/(this.canvas.clientWidth||360)));if(this.canvas.width!==800||this.canvas.height!==height){this.canvas.width=800;this.canvas.height=height;}const cw=this.canvas.width,ch=this.canvas.height,own=s.players.find(p=>p.id===this.you)||s.players.filter(p=>p.alive).sort((a,b)=>b.mass-a.mass)[0]||s.players[0];if(!own)return;if(!this.camera||this.camera.id!==own.id)this.camera={id:own.id,x:own.x,y:own.y};const smooth=this.reduced?1:1-Math.exp(-dt*9);this.camera.x=(this.camera.x+delta(own.x,this.camera.x,W)*smooth+W)%W;this.camera.y=(this.camera.y+delta(own.y,this.camera.y,H)*smooth+H)%H;const cx=this.camera.x,cy=this.camera.y,zoom=.92,project=(x,y)=>[cw/2+delta(x,cx,W)*zoom,ch*.42+delta(y,cy,H)*zoom];c.fillStyle=s.arena==='twilight'?'#27334b':s.arena==='lagoon'?'#174f64':'#244f42';c.fillRect(0,0,cw,ch);for(let i=0;i<60;i++){const x=(i*417)%W,y=(i*793)%H,[px,py]=project(x,y);c.fillStyle='#c6ddb314';c.beginPath();c.ellipse(px,py,35,14,i,0,7);c.fill();}c.strokeStyle='#cee5cd09';c.lineWidth=1;for(let x=0;x<W;x+=100){const[px]=project(x,cy);c.beginPath();c.moveTo(px,0);c.lineTo(px,ch);c.stroke();}for(let y=0;y<H;y+=100){const[,py]=project(cx,y);c.beginPath();c.moveTo(0,py);c.lineTo(cw,py);c.stroke();}for(const f of s.food){const[x,y]=project(f.x,f.y);if(x<-20||x>cw+20||y<-20||y>ch+20)continue;c.fillStyle=colors[f.color%6];c.shadowColor=c.fillStyle;c.shadowBlur=7;c.beginPath();c.arc(x,y,5+f.value,0,7);c.fill();}c.shadowBlur=0;for(const p of s.players){if(!p.alive)continue;const points=p.body.map(b=>project(...b)),head=project(p.x,p.y);c.lineJoin=c.lineCap='round';c.strokeStyle='#103440';c.lineWidth=26;c.beginPath();let previous;for(const b of [...points].reverse().concat([head])){if(!previous||Math.hypot(b[0]-previous[0],b[1]-previous[1])>300)c.moveTo(...b);else c.lineTo(...b);previous=b;}c.stroke();c.strokeStyle=p.color;c.lineWidth=20;c.stroke();c.strokeStyle='#ffffff30';c.lineWidth=4;c.stroke();c.save();c.translate(...head);c.rotate(p.angle);c.fillStyle=p.color;c.beginPath();c.arc(0,0,13,0,7);c.fill();for(const y of [-6,6]){c.fillStyle='#fff9e4';c.beginPath();c.arc(6,y,5,0,7);c.fill();c.fillStyle='#143442';c.beginPath();c.arc(8,y,2.4,0,7);c.fill();}c.restore();if(!p.bot)this.avatar(p,head[0],head[1]-35,13);if(p.immuneUntil>s.time){c.strokeStyle='#eaffba';c.lineWidth=2;c.setLineDash([4,6]);c.beginPath();c.arc(...head,24,0,7);c.stroke();c.setLineDash([]);}}if(!this.reduced)for(const e of this.effects){const[x,y]=project(e.x,e.y);c.globalAlpha=Math.max(0,e.life/.65);c.strokeStyle=e.color||'#fff0b2';c.lineWidth=3;c.beginPath();c.arc(x,y,(1-e.life/.65)*65,0,7);c.stroke();c.globalAlpha=1;}return;}
 if(this.canvas.width!==1200||this.canvas.height!==800){this.canvas.width=1200;this.canvas.height=800;}const cw=1200,ch=800;const alive=s.players.filter(p=>p.alive),leader=alive.slice().sort((a,b)=>b.mass-a.mass||a.number-b.number)[0]||s.players[0];if(!leader)return;this.drone=followCamera(this.drone,leader,s.world,this.t,dt,this.reduced);
 const project=p=>({x:450+p.x*520/p.z,y:400-p.y*520/p.z,z:p.z});
 const pt=(u,v)=>{const world=surface(u,v),point=cameraSpace(world,this.drone);return {...point,light:Math.max(0,Math.sin(v)*.7+Math.cos(v)*Math.sin(u-.4)*.3)};};
 const bg=c.createRadialGradient(520,380,20,550,400,680);bg.addColorStop(0,'#233d54');bg.addColorStop(1,'#0b172c');c.fillStyle=bg;c.fillRect(0,0,cw,ch);for(let i=0;i<80;i++){c.fillStyle='#bed6e533';c.fillRect((i*179)%cw,(i*97)%ch,1.5,1.5);}c.save();c.translate(555,625);c.scale(1,.2);const shadow=c.createRadialGradient(0,0,0,0,0,330);shadow.addColorStop(0,'#02091599');shadow.addColorStop(1,'#02091500');c.fillStyle=shadow;c.beginPath();c.arc(0,0,330,0,7);c.fill();c.restore();const quads=[];
 for(let a=0;a<96;a++)for(let b=0;b<40;b++){
  const u0=a/96*Math.PI*2,v0=b/40*Math.PI*2,points=[pt(u0,v0),pt(u0+Math.PI/48,v0),pt(u0+Math.PI/48,v0+Math.PI/20),pt(u0,v0+Math.PI/20)];
  const clipped=clipNear(points);if(clipped.length<3)continue;
  quads.push({points:clipped.map(project),depth:points.reduce((n,p)=>n+p.z,0)/4,light:points.reduce((n,p)=>n+p.light,0)/4,a,b});
 }
 quads.sort((a,b)=>b.depth-a.depth);c.save();c.beginPath();c.rect(0,0,900,ch);c.clip();
 for(const q of quads){const hue=s.arena==='twilight'?250:s.arena==='lagoon'?189:151,light=17+q.light*27+(q.a%12===0||q.b%10===0?4:0);c.fillStyle=`hsl(${hue},30%,${light}%)`;c.strokeStyle='#d4e7c316';c.lineWidth=.6;c.beginPath();q.points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fill();c.stroke();}
 // Hidden players remain visible on the flat overview; don't draw them through terrain.
 const visible=(point)=>{const target=surface(point.x/W*Math.PI*2,point.y/H*Math.PI*2),camera=this.drone.position;for(let i=1;i<24;i++){const t=i/24,x=camera[0]+(target[0]-camera[0])*t,y=camera[1]+(target[1]-camera[1])*t,z=camera[2]+(target[2]-camera[2])*t;if(Math.hypot(Math.hypot(x,z)-TORUS_MAJOR_RADIUS,y)<TORUS_MINOR_RADIUS-.025)return false;}return true;};
 // Draw the followed serpent on the surface; the other players keep their avatar markers.
 c.lineCap=c.lineJoin='round';c.strokeStyle=leader.color;c.lineWidth=13;c.beginPath();let connected=false;
 for(const b of [...(leader.body||[])].reverse().concat([[leader.x,leader.y]])){
  const point=pt(b[0]/W*Math.PI*2,b[1]/H*Math.PI*2);if(point.z<.08||!visible({x:b[0],y:b[1]})){connected=false;continue;}
  const screen=project(point);if(connected)c.lineTo(screen.x,screen.y);else c.moveTo(screen.x,screen.y);connected=true;
 }
 c.stroke();c.strokeStyle='#ffffff66';c.lineWidth=3;c.stroke();
  for(const p of alive){const point=pt(p.x/W*Math.PI*2,p.y/H*Math.PI*2);if(point.z<.08||!visible(p))continue;const screen=project(point);if(p.bot){c.fillStyle=p.color;c.beginPath();c.arc(screen.x,screen.y,5,0,7);c.fill();}else{this.avatar(p,screen.x,screen.y,p.id===leader.id?23:15);if(p.id===leader.id){c.strokeStyle='#ffe197';c.lineWidth=2;c.beginPath();c.arc(screen.x,screen.y,30,0,7);c.stroke();}}}c.restore();
  // Unwrap the torus with its major circumference running vertically.
 // The game coordinates still wrap on both axes; only the overview is stretched.
 const mx=925,my=35,mapWidth=250,mapHeight=Math.round(mapWidth*TORUS_MAJOR_RADIUS/TORUS_MINOR_RADIUS);
 c.fillStyle='#0a243de8';c.fillRect(mx-12,my-12,mapWidth+24,mapHeight+55);
 c.strokeStyle='#c5dfce88';c.lineWidth=2;c.strokeRect(mx,my,mapWidth,mapHeight);
 c.strokeStyle='#a6c9c52d';c.lineWidth=1;
 for(let i=1;i<4;i++){c.beginPath();c.moveTo(mx+i*mapWidth/4,my);c.lineTo(mx+i*mapWidth/4,my+mapHeight);c.stroke();}
 for(let i=1;i<11;i++){c.beginPath();c.moveTo(mx,my+i*mapHeight/11);c.lineTo(mx+mapWidth,my+i*mapHeight/11);c.stroke();}
 for(const p of alive){const x=mx+p.y/H*mapWidth,y=my+p.x/W*mapHeight;if(p.bot){c.fillStyle=p.color;c.beginPath();c.arc(x,y,4,0,7);c.fill();}else{this.avatar(p,x,y,12);if(p.id===leader.id){c.strokeStyle='#ffe197';c.lineWidth=2;c.beginPath();c.arc(x,y,17,0,7);c.stroke();}}}
 c.font='16px Trebuchet MS,Arial';c.fillStyle='#adc8ca';c.textAlign='center';c.fillText('↔  ↕',mx+mapWidth/2,my+mapHeight+26);c.textAlign='left';c.font='bold 23px Trebuchet MS,Arial';c.fillStyle='#f3dea5';const leaderName=this.profiles[leader.id]?.name||(leader.bot?'Bot '+(leader.number-8):'#'+leader.number);c.fillText('★ '+leaderName,55,70);c.font='13px Trebuchet MS,Arial';c.fillStyle='#b6d5ce';c.fillText(String(Math.floor(leader.mass)),55,96);
 }

}
